library:
  source-dirs: src
tests:
  name-generator-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - name-generator
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- random
- pcre-light
- regex-posix
- base >= 4.7 && < 5
name: name-generator
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/name-generator
license: BSD3
executables:
  name-generator-exe:
    source-dirs: app
    main: name_generator.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - name-generator
description: Please see the README on GitHub at <https://github.com/githubuser/name-generator#readme>
